language: python
python: "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - flake8 crypto bruteforce test.py
  - py.test --cov=crypto --cov=bruteforce tests.py
